name: Performance Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'jq4java-core/**'
      - 'jq4java-cli/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.18.0/hyperfine_1.18.0_amd64.deb
        sudo dpkg -i hyperfine_1.18.0_amd64.deb
    
    - name: Build jq4java
      run: mvn clean package -DskipTests
    
    - name: Run benchmarks
      run: |
        cd benchmarks
        bash run-benchmarks.sh
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmarks/results.md
